"""initial schema

Revision ID: 3134bad4a623
Revises: 
Create Date: 2026-05-14 22:49:35.450589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3134bad4a623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('data_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('csv_upload', 'odk_submission', 'api_connector', 'manual_entry', name='datasource'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('odk_form_id', sa.String(length=255), nullable=True),
    sa.Column('odk_submission_id', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('quarantine_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_lineage'))
    )
    op.create_table('emission_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('fuel_or_material', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('co2_factor', sa.Float(), nullable=False),
    sa.Column('ch4_factor', sa.Float(), nullable=False),
    sa.Column('n2o_factor', sa.Float(), nullable=False),
    sa.Column('hfc_factor', sa.Float(), nullable=False),
    sa.Column('pfc_factor', sa.Float(), nullable=False),
    sa.Column('sf6_factor', sa.Float(), nullable=False),
    sa.Column('nf3_factor', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Enum('DEFRA', 'IPCC', 'EPA', 'IEA', 'custom', name='factorsource'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factors'))
    )
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.Enum('oil_and_gas', 'manufacturing', 'agriculture', 'financial_services', 'technology', 'retail', 'transportation', 'construction', 'energy_utilities', 'other', name='industrytype'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('reporting_currency', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations'))
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_sites_organisation_id_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    op.create_index('idx_sites_geom', 'sites', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.Enum('absolute', 'intensity', name='targettype'), nullable=False),
    sa.Column('scope_coverage', sa.Enum('scope_1_only', 'scope_1_2', 'scope_1_2_3', name='scopecoverage'), nullable=False),
    sa.Column('baseline_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('baseline_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('target_reduction_pct', sa.Float(), nullable=False),
    sa.Column('target_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('aligned_to', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_targets_organisation_id_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    op.create_table('activity_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('data_lineage_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.Enum('scope_1', 'scope_2', 'scope_3', name='scopetype'), nullable=False),
    sa.Column('scope_2_method', sa.Enum('location_based', 'market_based', name='scope2method'), nullable=True),
    sa.Column('ghg_category', sa.String(length=100), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('fuel_or_material', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'validated', 'quarantined', 'calculated', name='datastatus'), nullable=False),
    sa.Column('is_flagged_duplicate', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_tier', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_lineage_id'], ['data_lineage.id'], name=op.f('fk_activity_records_data_lineage_id_data_lineage')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_activity_records_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_records'))
    )
    op.create_table('emission_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_record_id', sa.UUID(), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=False),
    sa.Column('co2_kg', sa.Float(), nullable=False),
    sa.Column('ch4_kg', sa.Float(), nullable=False),
    sa.Column('n2o_kg', sa.Float(), nullable=False),
    sa.Column('hfc_kg', sa.Float(), nullable=False),
    sa.Column('pfc_kg', sa.Float(), nullable=False),
    sa.Column('sf6_kg', sa.Float(), nullable=False),
    sa.Column('nf3_kg', sa.Float(), nullable=False),
    sa.Column('co2_co2e', sa.Float(), nullable=False),
    sa.Column('ch4_co2e', sa.Float(), nullable=False),
    sa.Column('n2o_co2e', sa.Float(), nullable=False),
    sa.Column('hfc_co2e', sa.Float(), nullable=False),
    sa.Column('pfc_co2e', sa.Float(), nullable=False),
    sa.Column('sf6_co2e', sa.Float(), nullable=False),
    sa.Column('nf3_co2e', sa.Float(), nullable=False),
    sa.Column('total_co2e_kg', sa.Float(), nullable=False),
    sa.Column('total_co2e_tonnes', sa.Float(), nullable=False),
    sa.Column('gwp_version', sa.Enum('AR5', 'AR6', name='gwpversion'), nullable=False),
    sa.Column('factor_fallback_used', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_record_id'], ['activity_records.id'], name=op.f('fk_emission_records_activity_record_id_activity_records')),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], name=op.f('fk_emission_records_emission_factor_id_emission_factors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_records')),
    sa.UniqueConstraint('activity_record_id', name=op.f('uq_emission_records_activity_record_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('emission_records')
    op.drop_table('activity_records')
    op.drop_table('targets')
    op.drop_index('idx_sites_geom', table_name='sites', postgresql_using='gist')
    op.drop_table('sites')
    op.drop_table('organisations')
    op.drop_table('emission_factors')
    op.drop_table('data_lineage')
    # ### end Alembic commands ###
